config/routes.rb
Vacuum::Application.routes.draw do
  # API Routes
  namespace :api do
    namespace :v1 do
      resources :errors
      resources :projects
    end
  end

  # Devise model mapping
  devise_for :users,
    :controllers => {
      :confirmations      => 'user/confirmations',
      :omniauth_callbacks => 'user/omniauth_callbacks',
      :passwords          => 'user/passwords',
      :registrations      => 'user/registrations',
      :sessions           => 'user/sessions',
      :unlocks            => 'user/unlocks'
  }

  # Devise scoped routes
  devise_scope :user do
    get '/account'       => 'user/registrations#edit',  as: 'account'
    get '/login'         => 'user/sessions#new',        as: 'login'
    get '/logout'        => 'user/sessions#destroy',    as: 'logout'
    get '/signup'        => 'user/registrations#new',   as: 'signup'
    get '/forgot'        => 'user/passwords#new',       as: 'forgot_password'
  end

  # Static pages
  get '/pricing'         => 'pages#pricing',            as: 'pricing'

  # Standard Resourcing
  resources :billing
  resources :projects do
    resources :errors do
      collection do
        post :group_resolve
      end
      member do
        get :resolve
      end
    end
    resources :collaborators
    resources :notifications
  end

  # Development specific testing routes
  if Rails.env.development?
    match '/logger/:id/err'   => 'home#errors', :via => [:get, :post]
    match '/logger'           => 'home#errors', :via => [:get, :post]

    # DJ Monitor
    match '/dj' => DelayedJobWeb, :anchor => false

    # Preview all emails with routes like followed
    mount AdminPreview  => 'admin_mail'
    mount ErrorPreview  => 'error_mail'
    mount UserPreview   => 'user_mail'
  end

  # Root the application
  authenticated :user do
    root :to => 'projects#index'
  end

  root to: 'home#index'
end

app/views/layouts/includes/_payment_modal.html.haml
- if user_signed_in?
  #upgradeAccount.reveal-modal{:class => "[expand, xlarge, large, medium, small]"}
    %h2 Upgrade Required
    %p
      Please help us by upgrading and paying for your account. We will give you 5 projects with unlimited error tracking and logging for one yearly fee.
      %br
      %div{align: 'center'}
        %h5 Current annual price
        %h3 $25.99
        %br
        %a.button.round.large.alert{"data-reveal-id" => "chargeCard", :href => "#"} Upgrade
    %a.close-reveal-modal ×

  #chargeCard.reveal-modal{:class => "[expand, xlarge, large, medium, small]"}
    %h2 Upgrade to Vacuum Pro
    %p We're excited to have you begin cleaning up your Javascript messes. Complete the form below to get going.
    .row
      .large-4.columns
        %dl
          %dt Total
          %dd $150.00
      .large-4.columns
        %img{src: 'http://cdn.creditcardimagelogos.com/logos/new/credit_card_logos_31.gif'}
    %p
      %span.payment-errors
      = form_tag billing_index_path, :id => "charge_form", :method => :post, :remote => true do
        = label_tag(:card_number, "Card Number")
        = text_field_tag 'card_number', '', placeholder: 'xxxx-xxxx-xxxx-xxxx'
        .row
          .large-4.columns
            = label_tag(:card_cvc, "CVC")
            = text_field_tag 'card_cvc', nil, :size => 5
          .large-4.columns
            = label_tag(:expiry_month, "Expiration Month")
            = text_field_tag 'expiry_month', nil, :size => 10, placeholder: 'MM'
          .large-4.columns
            = label_tag(:expiry_year, "Expiration Year")
            = text_field_tag 'expiry_year', nil, :size => 10, placeholder: 'YY'

        = hidden_field_tag 'user_id', current_user.id

        = submit_tag "Upgrade", class: "button round success"
    %a.close-reveal-modal ×

  - if current_user.needs_to_pay? && SETTINGS[:show_upgrade_modal]
    :javascript
      $(document).ready(function() {
        $("#upgradeAccount").reveal();
      });

app/views/layouts/includes/_user.html.haml
- $user = {current_user_uuid: '', current_user_email: ''}
- if user_signed_in?
  - $user[:current_user_uuid]  = current_user.identifier
  - $user[:current_user_email] = current_user.email

app/views/layouts/includes/_user_voice.html.haml
<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/XxpiBeR9ENJXBxoN4I9MMQ.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<!-- A tab to launch the Classic Widget -->
<script>
UserVoice = window.UserVoice || [];
UserVoice.push(['showTab', 'classic_widget', {
mode: 'full',
primary_color: '#49bf98',
link_color: '#d63f44',
default_mode: 'feedback',
forum_id: 208213,
tab_label: 'Feedback & Support',
tab_color: '#49bf98',
tab_position: 'middle-right',
tab_inverted: false
}]);
</script>