config/routes.rb
Vacuum::Application.routes.draw do
  # API Routes
  namespace :api do
    namespace :v1 do
      resources :errors
      resources :projects
    end
  end

  # Devise model mapping
  devise_for :users,
    :controllers => {
      :confirmations      => 'user/confirmations',
      :omniauth_callbacks => 'user/omniauth_callbacks',
      :passwords          => 'user/passwords',
      :registrations      => 'user/registrations',
      :sessions           => 'user/sessions',
      :unlocks            => 'user/unlocks'
  }

  # Devise scoped routes
  devise_scope :user do
    get '/account'       => 'user/registrations#edit',  as: 'account'
    get '/login'         => 'user/sessions#new',        as: 'login'
    get '/logout'        => 'user/sessions#destroy',    as: 'logout'
    get '/signup'        => 'user/registrations#new',   as: 'signup'
    get '/forgot'        => 'user/passwords#new',       as: 'forgot_password'
  end

  # Static pages
  get '/pricing'         => 'pages#pricing',            as: 'pricing'

  # Standard Resourcing
  resources :billing
  resources :projects do
    resources :errors do
      collection do
        post :group_resolve
      end
      member do
        get :resolve
      end
    end
    resources :collaborators
    resources :notifications
  end

  # Development specific testing routes
  if Rails.env.development?
    match '/logger/:id/err'   => 'home#errors', :via => [:get, :post]
    match '/logger'           => 'home#errors', :via => [:get, :post]

    # DJ Monitor
    match '/dj' => DelayedJobWeb, :anchor => false

    # Preview all emails with routes like followed
    mount AdminPreview  => 'admin_mail'
    mount ErrorPreview  => 'error_mail'
    mount UserPreview   => 'user_mail'
  end

  # Root the application
  authenticated :user do
    root :to => 'projects#index'
  end

  root to: 'home#index'
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include DefaultAttributeSetters

  field :name,        type: String
  field :url,         type: String
  field :enabled,     type: Boolean, default: true
  field :api_key,     type: String
  field :identifier,  type: String

  ### Associations
  belongs_to :user
  has_many :errors, autosave: true, :dependent => :destroy
  has_many :collaborators, autosave: true, :dependent => :destroy
  has_many :notifications, autosave: true, :dependent => :destroy

  ### Validations
  validates :name, :presence => true, :uniqueness => { :scope => :user_id }
  validates :url,  :presence => true, :uniqueness => { :scope => :user_id }

  def to_js
    # host = Rails.env.development? || Rails.env.test? ? 'localhost:3000' : 'vacuum.io'
    script = "<script type=\"text/javascript\">" +
      "var _vacuum = _vacuum || []; " +
      "_vacuum.push(['_setKey', '"+self.api_key+"']);" +
      "_vacuum.push(['_setIdentifier', '"+self.identifier+"']);" +
      "_vacuum.push(['debug', false]);" +
      "(function() {" +
        "var vs = document.createElement('script'); vs.type = 'text/javascript'; vs.async = true;" +
        "vs.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '#{SETTINGS[:cloudfront_alias]}/vacuum.js';" +
        "var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(vs, s);" +
      "})();" +
      "</script>"
    return script
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::ApiController  
  before_filter :clean_params,    :only => [:index, :create]
  before_filter :load_project,    :only => [:index, :create]
    
  # index
  # This method will return a site {} hash as well as log_entries {} 
  # hash of data for the given api_key's site's log entries.
  def index
    @project = Project.where(api_key: params[:api_key])[0]
    render json: {project: @project.as_json(only: project_permissions(:only))}, status: 200, callback: params[:callback]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper
  before_filter :authenticate_user!
  before_filter :load_project, :only => [:show, :update, :destroy]
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end
  
  def index
    @projects = current_user.projects.paginate(page: params[:page], per: 2)
    current_user.collaborators.collect { |c| @projects << c.project }
    authorize! :read, Project, message: project_read_deny
  end
  
  def new
    authorize! :create, Project, message: project_create_deny(current_user)
    new_project
  end
  
  def create
    authorize! :create, Project, message: project_create_deny(current_user)
    create_project(params)
  end
  
  def show
    authorize! :read, @project, message: project_read_deny
  end
  
  def update
    authorize! :update, @project, message: project_read_deny
    update_project(@project, params)
  end
  
  def destroy
    authorize! :destroy, @project, message: project_read_deny
    destroy_project(@project)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def create_project(params)
    if params[:project][:name].nil? || params[:project][:name].empty? ||
      params[:project][:url].nil? || params[:project][:url].empty?
      flash[:error] = "Incorrect parameters missing or passed. Please try again."
      redirect_to new_project_path
      return false
    end
    
    @project = current_user.projects.build(params[:project])
    
    if @project.save
      flash[:success] = "Awesome! Lets get you logging some errors now."
      redirect_to project_path(@project)
    else
      flash[:alert] = "Ooops, #{@project.errors.messages.collect { |k,v| "#{k.upcase} #{v.first}" }.join(',').gsub(',', ', ')}"
      render :new 
    end
  end
  
  def new_project
    @project = current_user.projects.build
  end
  
  def update_project(project, params)
    if project.update_attributes!(params[:project])
      flash[:success] = "Project successfully updated."
    else
      flash[:alert] = "Ooops, #{project.errors.messages.collect { |k,v| "#{k.upcase} #{v.first}" }.join(',').gsub(',', ', ')}"
    end
    
    redirect_to project_path(project, anchor: 'settings')
  end
  
  def destroy_project(project)
    if project.destroy
      flash[:success] = "Project successfully deleted."
      redirect_to projects_path
    else
      flash[:alert] = "Ooops, #{project.errors.messages.collect { |k,v| "#{k.upcase} #{v.first}" }.join(',').gsub(',', ', ')}"
      redirect_to project_path(project)
    end
  end
  
  def load_project
    @project = Project.find(params[:id])
  end
  
  def project_read_deny
    "Permission denied."
  end
  
  def project_create_deny(current_user)
    "You need to upgrade your account before you can add more projects."
  end
end

app/views/projects/_index_row.html.haml
%tr
  %td
    %strong= link_to project.name, project_errors_path(project)
  - if project.errors.count == 0
    %td
      %em n/a
  - else
    %td= time_ago_in_words(project.errors.desc(:updated_at).first.updated_at)
  %td= project.errors.unresolved.count
  %td= project.errors.count
  %th
    .small.button.dropdown.round{href:  "#", data: {dropdown: 'config-dropdown'}} Configuration
    %ul#config-dropdown.f-dropdown{data: {dropdown_content: true}}
      %li
        %a{href: project_path(project, anchor: 'setup')} Setup
      %li
        %a{href: project_path(project, anchor: 'notifications')} Notifications
      %li
        %a{href: project_path(project, anchor: 'collaborators')} Collaborators
      %li
        %a{href: project_path(project, anchor: 'settings')} Settings
      %li.divider
      %li
        = link_to project_path(project), :method => :delete, confirm: "Are you sure you want to delete the '#{project.name}' project?" do
          %i.icon-ban-circle
          Delete project

app/views/projects/_project.html.haml
%tr
  %td
    %strong= link_to project.name, project_errors_path(project)
  - if project.errors.count == 0
    %td
      %em n/a
  - else
    %td= time_ago_in_words(project.errors.desc(:updated_at).first.updated_at)
  %td= project.errors.unresolved.count
  %td= project.errors.count
  %th
    .small.button.dropdown.round{href:  "#", data: {dropdown: "config-dropdown-#{project.id}"}} Configuration
    %ul.f-dropdown{id: "config-dropdown-#{project.id}", data: {dropdown_content: true}}
      %li
        %a{href: project_path(project, anchor: 'setup')} Setup
      %li
        %a{href: project_path(project, anchor: 'notifications')} Notifications
      %li
        %a{href: project_path(project, anchor: 'collaborators')} Collaborators
      %li
        %a{href: project_path(project, anchor: 'settings')} Settings
      %li.divider
      %li
        = link_to project_path(project), :method => :delete, confirm: "Are you sure you want to delete the '#{project.name}' project?" do
          %i.icon-ban-circle
          Delete project

app/views/projects/edit.html.haml
.row
  .large-12.columns
    %h2 Manage #{@project.name}
    %dl.tabs
      %dd.active
        %a{:href => "#setup"} Setup
      %dd
        %a{:href => "#notification"} Notification
      %dd
        %a{:href => "#collaborators"} Collaborators
      %dd
        %a{:href => "#settings"} Settings
    %ul.tabs-content
      %li#setupTab.active
        %h3 Javascript Installation
        %p
          Add this snippet directly after the
          %code= "<head>"
          tag in your application.
          %pre
            = @project.to_js
        %div{align: 'right'}
          = link_to "I've completed this step", project_errors_path(@project), :class => 'success button'

        %h4 Automatic Logging
        %p
          Start logging errors automatically, these will trigger the
          %span{class: 'label'} system
          notification.
          %br
          %pre
            vacuum.window_error = true;

        %h4 Manual Logging
        %p
          Start logging errors manually, these will trigger the
          %span{class: 'alert label'} error
          or
          %span{class: 'warn label'} warn
          notification.
          %br
          %pre
            vacuum.warn('wonky redirect right here, watch the response');
          %br
          %pre
            vacuum.error('.ajax.complete never returns');


      %li#notificationTab
        %h2 Notify the correct people
        %p
          - unless @project.notifications.empty?
            %h4 People who will be notified for errors
            #notification_members
              %table.table
                %thead
                  %tr
                    %th Name
                    %th Email
                    %th Options
                  %tbody
                    - @project.notifications.each do |notifier|
                      %tr
                        %td= notifier.name
                        %td= notifier.email
                        %th
                          .small.button.dropdown.round{:href => "#"}
                            Configuration
                            %ul
                              %li
                                %a{:href => edit_project_notification_path(@project, notifier)} Edit
                              %li.divider
                              %li
                                = link_to "Delete", project_notification_path(@project, notifier), :method => :delete, :confirm => "Are you sure you want to delete this person?"


        %p
          #notifications_error
        %p
          %h4 Add a new contact
          #notifications_new
            - @notification = @project.notifications.build
            = form_for @notification, :url => project_notifications_path(@project.id), :html => { :id => "notifications_form" } do |f|
              = f.label :name
              = f.text_field :name
              #notifications_name_error
              %br
              = f.label :email
              = f.text_field :email
              #notifications_email_error
              = hidden_field_tag 'notification_project_id', @project.id
              = f.submit 'Create', :class => 'button round'
              = link_to 'Cancel', request.referrer
      %li#collaboratorsTab
        %h3 Collaborators
        %p
          Coming soon...
      %li#settingsTab
        .row
          .large-5.columns
            %h3= "Edit #{@project.name}"
            = form_for @project do |f|
              = f.label :name
              = f.text_field :name
              %br
              = f.label :url
              = f.text_field :url
              = f.submit 'Update', :class => 'button round'
              = link_to 'Cancel', request.referrer
          .large-6.columns
            %h3 Configuration
            %p
              Be sure to install this js after the
              %code= "<head>"
              tag in your application.
              %textarea{rows: 4}
                = @project.to_js

            %h3 API Key
            %p= @project.api_key

    %a.button.round.small{href: request.referrer} Back

app/views/projects/index.html.haml
.row
  .large-12.columns
    - if @projects.empty?
      .panel
        %h2= link_to "Create your first project", new_project_path
    - else
      %h2 Your Projects
      %table.table
        %thead
          %tr
            %th Name
            %th Last Error
            %th Unesolved
            %th Total
            %th{width: 150}
          %tbody
            = render @projects
      %div{align: 'left'}
        %a.success.button.round{href: new_project_path}
          %i.foundicon-plus
          Create a project
        = will_paginate(@projects)

app/views/projects/new.html.haml
.row
  .large-6.columns.large-offset-3
    %h2 Create a new project
    .panel
      = form_for @project do |f|
        = f.label :name
        = f.text_field :name
        %br
        = f.label :url
        = f.text_field :url
        = f.submit 'Create', :class => 'button round'
        = link_to 'Cancel', request.referrer

app/views/projects/show.html.haml
.row
  .large-12.columns
    .panel
      .section-container.tabs{data: {section: true, options: 'deep_linking: true;'}}
        %section.active
          %p.title{data: {section_title: true}}
            %a{href: '#setup'} Setup
          .content{data: {slug: 'setup', section_content: true}}
            %h2 Javascript Installation
            %p
              Add this snippet directly after the
              %code= "<head>"
              tag in your application and before any other javascript code/dependencies are loaded. The code in this script will only ever be instantiated
              on an error. Therefore you are only just loading in the size of the script. When an error is triggered, this code will run.
              %br
              %br
              Never change/edit or try to minify this piece of code. For we use the
              %code _vacuum
              object amongst your application and in our listener.
              %br
              %br
              %textarea{:cols => "50", :rows => "6", :id => 'codebox'}= @project.to_js
            %div{align: 'right'}
              = link_to "I've completed this step", project_errors_path(@project), :class => 'success button round'

        %section
          %p.title{data: {section_title: true}}
            %a{href: '#notifications'} Notifications
          .content{data: {slug: 'notifications', section_content: true}}
            %h2 Error Notifications
            %h6.subheader Sends an email to the right person when a single error occurs.
            %p
              - unless @project.notifications.empty?
                #notification_members
                  %table.table
                    %thead
                      %tr
                        %th Name
                        %th Email
                        %th Options
                      %tbody
                        - @project.notifications.each do |notifier|
                          %tr
                            %td= notifier.name
                            %td= notifier.email
                            %th
                              .small.button.round.dropdown{:href => "#", data: {dropdown: 'config-dropdown'}}
                                Configuration
                              %ul#config-dropdown.f-dropdown{data: {dropdown_content: true}}
                                %li
                                  %a{:href => edit_project_notification_path(@project, notifier)} Edit
                                %li.divider
                                %li
                                  = link_to "Delete", project_notification_path(@project, notifier), :method => :delete, :confirm => "Are you sure?"
            %p
              #notifications_error
              %div{:align => 'left'}
                %a.success.button.round{"data-reveal-id" => "newNotifier"}
                  %i.foundicon-plus
                  New Contact

        %section
          %p.title{data: {section_title: true}}
            %a{href: '#collaborators'} Collaborators
          .content{data: {slug: 'collaborators', section_content: true}}
            %h2 Collaborators
            %h6.subheader Gives another Vacuum user read access to your project.
            %p
              - unless @project.collaborators.empty?
                #collaborator_members
                  %table.table
                    %thead
                      %tr
                        %th Email
                        %th Options
                      %tbody
                        - @project.collaborators.each do |collaborator|
                          %tr
                            %td= collaborator.email
                            %th
                              .small.button.round.dropdown{:href => "#", data: {dropdown: 'config-dropdown'}}
                                Configuration
                              %ul#config-dropdown.f-dropdown{data: {dropdown_content: true}}
                                %li
                                  %a{:href => edit_project_collaborator_path(@project, collaborator)} Edit
                                %li.divider
                                %li
                                  = link_to "Delete", project_collaborator_path(@project, collaborator), :method => :delete, :confirm => "Are you sure?"
            %p
              #notifications_error
              %div{:align => 'left'}
                %a.success.button.round{"data-reveal-id" => "newCollaborator"}
                  %i.foundicon-plus
                  New Collaborator

        %section
          %p.title{data: {section_title: true}}
            %a{href: '#settings'} Settings
          .content{data: {slug: 'settings', section_content: true}}
            .row
              .large-5.columns
                %h2= "Edit #{@project.name}"
                = form_for @project do |f|
                  = f.label :name
                  = f.text_field :name
                  %br
                  = f.label :url
                  = f.text_field :url
                  = f.submit 'Update', :class => 'button round success'
                  = link_to 'Cancel', request.referrer
              .large-6.columns
                %h2 API Key
                %p= @project.api_key

                %h2 API Identifier
                %p= @project.identifier
                
                %p
                  = link_to project_path(@project), :method => :delete, confirm: "Are you sure you want to delete the '#{@project.name}' project?" do
                    %i.icon-ban-circle
                    Delete project
    %a.button.round.small{href: project_errors_path(@project)} < Back to logs

- content_for :modals do
  #newNotifier.reveal-modal
    %h5 Add a new person to be notified on error
    #notifications_new
      - @notification = @project.notifications.build
      = form_for @notification, :url => project_notifications_path(@project.id), :html => { :id => "notifications_form" } do |f|
        = f.label :name
        = f.text_field :name
        #notifications_name_error
        %br
        = f.label :email
        = f.text_field :email
        #notifications_email_error
        = hidden_field_tag 'notification_project_id', @project.id
        = f.submit 'Create', :class => 'button round success'
        %a.close-reveal-modal x
  #newCollaborator.reveal-modal
    %h5 Share access to this project
    #notifications_new
      - @collaborator = @project.collaborators.build
      = form_for @collaborator, :url => project_collaborators_path(@project.id), :html => { :id => "collaborators_form" } do |f|
        = f.label :email
        = f.text_field :email
        #collaborators_email_error
        = hidden_field_tag 'collaborator_project_id', @project.id
        = f.submit 'Create', :class => 'button success round'
        %a.close-reveal-modal x